# Generated by Django 2.2.6 on 2019-10-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHasTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_hash', models.CharField(max_length=32)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image_type', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_url', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imageSearch.Images')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.ManyToManyField(through='imageSearch.ImageHasTags', to='imageSearch.Tags'),
        ),
        migrations.AddField(
            model_name='imagehastags',
            name='image_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageSearch.Images'),
        ),
        migrations.AddField(
            model_name='imagehastags',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageSearch.Tags'),
        ),
    ]
