# Generated by Django 2.2.6 on 2019-10-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagehastags',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='imagehastags',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
