# Generated by Django 2.2.7 on 2019-11-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageSearch', '0002_auto_20191014_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
